### ISSUE TITLE
Charlie has been shrekt

### ISSUE THREAD

**Issue by J-K-Gobat** [Charlie92/Charlie92.github.io#4]
( ͡° ͜ʖ ͡°)

**Comment by Charlie92** [comment]
K

**Comment by J-K-Gobat** [comment]
hue

**Comment by J-K-Gobat** [comment]
ja

**Comment by Charlie92** [comment]
Please Stop

**Comment by J-K-Gobat** [comment]
i

**Comment by J-K-Gobat** [comment]
am

**Comment by J-K-Gobat** [comment]
better than charlie

**Comment by J-K-Gobat** [comment]
do you even play oblivion

**Comment by J-K-Gobat** [comment]
pop

**Comment by SwyrWolf** [comment]
:kr:

**Comment by SwyrWolf** [comment]
The koreans had me play dota 2 with them.

**Comment by Charlie92** [comment]
Hi Gavin

**Comment by J-K-Gobat** [comment]
bye gavin

**Comment by SwyrWolf** [comment]
ㅋㅅㅋ

**Comment by Charlie92** [comment]
Whats that?

**Comment by J-K-Gobat** [comment]
ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ

**Comment by J-K-Gobat** [comment]
blankㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ

**Comment by J-K-Gobat** [comment]
blankㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ

**Comment by J-K-Gobat** [comment]
vㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ Beep

**Comment by J-K-Gobat** [comment]
cㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ Beep

**Comment by J-K-Gobat** [comment]
I like chicken 
vㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ ㅋㅅㅋ

**Comment by SwyrWolf** [comment]
Charlie it's a Korean emoticon.

**Comment by Charlie92** [comment]
Gavin poke Logan

**Comment by SwyrWolf** [comment]
ㅋㅋㅋ I did it

**Comment by Charlie92** [comment]
Good job

**Comment by J-K-Gobat** [comment]
its all ogre now

**Comment by SwyrWolf** [comment]
ㅋㅋㅋ = lol in Korean

**Comment by Charlie92** [comment]
Stop bullying Jarerd

**Comment by Charlie92** [comment]
Jared

**Comment by J-K-Gobat** [comment]
whos bullying me

**Comment by J-K-Gobat** [comment]
lol

**Comment by J-K-Gobat** [comment]
Fight me

**Comment by J-K-Gobat** [comment]
i will

**Comment by J-K-Gobat** [comment]
charlie the hacker

**Comment by SwyrWolf** [comment]
o
